version: 2.1
orbs:
  docker: circleci/docker@2.8.1  # Use the Docker Orb

jobs:
  build_and_push:
    executor: docker/docker  # Define the executor to use Docker environment
    steps:
      - checkout  # Check out source code
      # Enable Docker layer caching

      - docker/check:
          docker-username: $DOCKERHUB_USERNAME  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          docker-password: $DOCKERHUB_ACCESS_TOKEN
      - docker/build:  # Build Docker image
          image: $DOCKERHUB_USERNAME/myapp
          tag: 'latest'  # Multiple tags for the image

      - docker/push:  # Push Docker image
          image: $DOCKERHUB_USERNAME/myapp
          tag: 'latest'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push