version: 2.1
orbs:
  docker: circleci/docker@2.8.1  # Use the Docker Orb

jobs:
  build_and_push:
    executor: docker/docker  # Define the executor to use Docker environment
    steps:
      - checkout  # Check out source code
      # Enable Docker layer caching

      - docker/check  # Check for existing Docker image

      - run:  # Login to Docker Hub
          name: Log into Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - docker/build:  # Build Docker image
          image: $DOCKERHUB_USERNAME/myapp
          tag: 'latest'  # Multiple tags for the image

      - docker/push:  # Push Docker image
          image: $DOCKERHUB_USERNAME/myapp
          tag: 'latest'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push