# Docker image configuration
serviceAccount:
  create: true
  name: custom-service-account-name
image:
  repository: ksreenath801/myapp
  tag: latest
  pullPolicy: IfNotPresent

# Replica count
replicaCount: 2

# Application-specific configurations
appConfig:
  appName: demo-app
  environment: production

# Resources for the deployment
resources:
  requests:
    memory: "20Mi"
    cpu: "50m"
  limits:
    memory: "40Mi"
    cpu: "100m"

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: demo-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80