# values.yaml
image:
  repository: ksreenath801/myapp
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80

# resources:
#   limits:
#     cpu: "500m"
#     memory: "128Mi"
#   requests:
#     cpu: "250m"
#     memory: "64Mi"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []